### ISSUE TITLE
 Large Html conversion consume much memory

### ISSUE THREAD

**Issue by siegelzc** [openhtmltopdf/openhtmltopdf#1]
[Original issue](https://github.com/danfickle/openhtmltopdf/issues/962#issue-2096522730) by @Hikariqz

Hi guys,

I'm having an issue where converting a large HTML document to PDF is consuming a significant amount of memory. The HTML represents around 1200 pages, but the file size is only around 3MB.

When generating the PDF, I noticed my Java VM memory usage increasing up to around 1GB. I used a profiler to investigate further and found that a lot of byte arrays were being created during the PDF generation process. Most of the memory usage appeared to be occurring in calls to com.openhtmltopdf.css.newmatch.Condition#matches which involves java.lang.StringBuilder.toString or java.lang.StringBuilder.

![image](https://github.com/openhtmltopdf/openhtmltopdf/assets/15002786/2a2fabe9-9c8b-4005-b08c-428c60877ddc)

I'm hoping someone may be able to provide some help or insights on how I could optimize this process to use less memory. Converting such a large number of HTML pages to PDF seems to be straining the memory usage and I want to find a more efficient way to handle it.

Really appreciate it!

**Comment by Hikariqz** [comment]
Hi @siegelzc , I investigate a little bit more, according to Profiler, it looks like a lot of byte array was created by below code snippet. The return statement has a String append operation result into a lot byte array creation. I don't know what is use for but during my debugger it do get called many many times. I am thinking we need to find solution to avoid it or make it be reclaimed as soon as possible.
Just hope the information could gave us some clue. Thank you

`
@Override
        boolean matches(Object e, AttributeResolver attRes, TreeResolver treeRes) {
            if (attRes == null) {
                return false;
            }
            String c = attRes.getClass(e);
            if (c == null) {
                return false;
            }

            // This is much faster than calling `split()` and comparing individual values in a loop.
            // NOTE: In jQuery, for example, the attribute value first has whitespace normalized to spaces. But
            // in an XML DOM, space normalization in attributes is supposed to have happened already.
            return (" " + c + " ").indexOf(_paddedClassName) != -1;
        }
`

**Comment by siegelzc** [comment]
I might be missing something, but it's not clear to me where any byte arrays are being allocated here.

**Comment by Hikariqz** [comment]
Hi @siegelzc , I am just using a below very simple html for test with VM options -Xmx2g -Xms2g.  
[test.txt](https://github.com/openhtmltopdf/openhtmltopdf/files/14076114/test.txt)

**Comment by jochenberger** [comment]
We'll need to get rid of the String concatenation (`" " + c + " "`). This creates a new StringBuilder with backing byte arrays upon every invocation.

**Comment by Hikariqz** [comment]
Yes, I agree. Especially when a lot of css styles need to render, it allocates byte array frequently. Maybe I could also do some help on this, Would you mind I do some further investigate on this and try to figure out a way to improve it? @siegelzc

**Comment by jochenberger** [comment]
My suggestion would be to not store the padded class name in a field but the class name itself. This way we can avoid all those nasty concat and substring transformations. Then match the class name itself using indexOf and check for the spaces using char comparison with String indexes. 
I can try to create a PR but it's going to take me a few days at best.

**Comment by siegelzc** [comment]
Why aren't the byte arrays being cleaned up by the garbage collector?

**Comment by jochenberger** [comment]
They are. This is not a memory leak issue. But we can avoid them being created at all to save some GC time.

**Comment by hbenyahia-nickel** [comment]
Hello, has this fix been packaged into maven central repository ?

**Comment by siegelzc** [comment]
> Hello, has this fix been packaged into maven central repository ?

It has not. Any changes since the 1.1.4 release available on Maven Central are available through the GitHub package server. We want to get a deployment set up to Maven Central, but right now, GitHub packages is the only option to receive the most recent changes.

**Comment by xtermi2** [comment]
> > Hello, has this fix been packaged into maven central repository ?
> 
> It has not. Any changes since the 1.1.4 release available on Maven Central are available through the GitHub package server. We want to get a deployment set up to Maven Central, but right now, GitHub packages is the only option to receive the most recent changes.

You should document this in the README with the required maven settings like repo URL, groupeId, artifactId, etc.

**Comment by hmznckl** [comment]
Thank you @siegelzc for your reply
We want to test this fix in order to see if if it can enhance our performance issue but we can't use GitHub package server. Is there an other way use this fix please ?
