### ISSUE TITLE
Update the package description to pdfbox 3

### ISSUE THREAD

**Issue by 123Haynes** [openhtmltopdf/openhtmltopdf#10]
Hello,

while browsing this repo I noticed that the code has been updated to pdfbox 3, but the package description still references pdfbox 2 which is confusing.  

See: 
https://github.com/openhtmltopdf/openhtmltopdf/blob/main/openhtmltopdf-pdfbox/pom.xml#L29

Just a minor documentation change and not super important, but it should still be addressed I think😄

**Comment by siegelzc** [comment]
Updated the GitHub repo description as well.
