### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by madsop-nav** [openhtmltopdf/openhtmltopdf#13]
We should probably agree on a release process.

Including questions like:
- group id
- should we release to Maven central? If so, how's the setup there?

And also branching strategy. In https://github.com/openhtmltopdf/openhtmltopdf/pull/9#issuecomment-1956200468 , that lead to this issue, @ganomi suggested gitflow.

I find it easier, and sufficient, that every merge/commit to main triggers a new release. I doubt that there will be high amounts of work done here, so that it won't be that many releases either.

**Comment by ganomi** [comment]
I would follow @madsop-nav on this for now, as long as there is only minor changes being done.

**Comment by PavelTen** [comment]
We appreciate your efforts to continue developing openhtmltopdf and we 'd like to switch to a new version. However, we'd need an official maven central release before doing it. 
Do you have any estimates when we could expect a decision on new group id and 1.1.5(?) being released?

**Comment by madsop-nav** [comment]
> We appreciate your efforts to continue developing openhtmltopdf and we 'd like to switch to a new version. However, we'd need an official maven central release before doing it. Do you have any estimates when we could expect a decision on new group id and 1.1.5(?) being released?

Happy to hear. I'm starting looking into how to do Maven central releases now. As I'm new to it, I won't promise anything on how long it'll take, though.

**Comment by jonathansp** [comment]
> > We appreciate your efforts to continue developing openhtmltopdf and we 'd like to switch to a new version. However, we'd need an official maven central release before doing it. Do you have any estimates when we could expect a decision on new group id and 1.1.5(?) being released?
> 
> Happy to hear. I'm starting looking into how to do Maven central releases now. As I'm new to it, I won't promise anything on how long it'll take, though.

@madsop-nav thank you for your efforts ❤️ we're in the same situation as @PavelTen, waiting for a maven release. Please let us know if any help is required.

**Comment by hmznckl** [comment]
> > We appreciate your efforts to continue developing openhtmltopdf and we 'd like to switch to a new version. However, we'd need an official maven central release before doing it. Do you have any estimates when we could expect a decision on new group id and 1.1.5(?) being released?
> 
> Happy to hear. I'm starting looking into how to do Maven central releases now. As I'm new to it, I won't promise anything on how long it'll take, though.

Thank you so much for the work you are doing ❤️ Can't wait to start using this new version. We would be happy to help you guys in theses processes, please let us know 😉

**Comment by madsop-nav** [comment]
Jumping back in here with a quick update. We are now technically able to deploy to Maven Central, I've tested deploying artifacts there and it validated successfully.

There are some shortcuts and workarounds I've done along the way though that I want to clean up before we ship, so we're not ready to properly release nor announce yet, but we're getting there.

**Comment by madsop-nav** [comment]
> @madsop-nav I just noticed that the README states "An exception to this is the pdf-a testing module, which is licensed under the GPL. This module is not distributed to Maven Central and is for testing only.", but you have made some changes to publish this too. Was this a deliberate choice and the respective note should be removed or was this a mistake and it should get removed from Maven Central again?

Good catch. It wasn't deliberate from my side, and I didn't do anything in particular to make that one part of what's released to Maven Central, but I don't really see any problem with it either.

What are your takes on this, @siegelzc and @imario42 ?

**Comment by imario42** [comment]
Well, since that is an empty package, effectively just releasing a pom with a GPL dependency I have the gut feeling that I would prefer to not put that on Maven.
If the original author state that on various places ... so might be something we should follow?
I am wondering why it happened at all because the deploy plugin is marked to be skipped already anyways ...

**Comment by imario42** [comment]
openhtmltopdf-examples and openhtmltopdf-templates should habe been skipped also

**Comment by madsop-nav** [comment]
> Well, since that is an empty package, effectively just releasing a pom with a GPL dependency I have the gut feeling that I would prefer to not put that on Maven. If the original author state that on various places ... so might be something we should follow? I am wondering why it happened at all because the deploy plugin is marked to be skipped already anyways ...

The new `central-publishing-maven-plugin` has its own config, and it doesn't look like it cares about the existing config. So made https://github.com/openhtmltopdf/openhtmltopdf/pull/38 to address this concern.

**Comment by madsop-nav** [comment]
I think we have the release process sorted, so I'm closing this issue now. Feel free to create new, more specific issues (or PRs) if needed.

**Comment by imario42** [comment]
@madsop-nav : Great Job Mads! 🥇 Thank you!
