### ISSUE TITLE
Add a reference to this repo in danfickle's repo readme.

### ISSUE THREAD

**Issue by suchwerk** [openhtmltopdf/openhtmltopdf#16]
Maybe it's possible to add a reference to the new repo in danfickle's  openhtmltopdf repo. On the first sight it looks like that openhtmltopdf is not maintained anymore.

**Comment by siegelzc** [comment]
I would love to do that, but @danfickle has been unreachable, and hasn't been approving PRs. I could go submit a PR to edit the README over there, but I doubt he would see it and review in order to merge.

**Comment by madsop-nav** [comment]
The history behind this organization is in an issue discussion in the original repo: https://github.com/danfickle/openhtmltopdf/issues/921

Might be worth creating a new issue there named `ANNOUNCEMENT: Repo forked to new organization by volunteers` or something?

**Comment by suchwerk** [comment]
@madsop-nav:

It should not appear as a hostile takeover and should show respect to Dan, maybe something like this:

> Dear Community,
> 
> We want to inform you about recent developments regarding the project. Due to challenges with communication and maintenance, the project has been forked to a new organization by volunteers.
> 
> Acknowledgement:
> 
> Before we proceed, we want to acknowledge and thank @danfickle for his pivotal role as the founder and driving force behind this project. 
> 
> Next Steps:
> 
> In light of recent challenges, a group of volunteers has forked the project to a new organization to ensure its continued development. We extend an open invitation to @danfickle to rejoin us in this effort at any time.
> 
> How You Can Help:
> 
> We encourage community members to contribute to the new repository, submit pull requests, and participate in discussions to help shape the project's future.
> 
> Stay Updated:
> 
> To stay informed about the latest developments and participate in discussions, please visit the new repository [link to new repository].

**Comment by madsop-nav** [comment]
> @madsop-nav:
> 
> It should not appear as a hostile takeover and should show respect to Dan, maybe something like this:
> 
> > Dear Community,
> > We want to inform you about recent developments regarding the project. Due to challenges with communication and maintenance, the project has been forked to a new organization by volunteers.
> > Acknowledgement:
> > Before we proceed, we want to acknowledge and thank @danfickle for his pivotal role as the founder and driving force behind this project.
> > Next Steps:
> > In light of recent challenges, a group of volunteers has forked the project to a new organization to ensure its continued development. We extend an open invitation to @danfickle to rejoin us in this effort at any time.
> > How You Can Help:
> > We encourage community members to contribute to the new repository, submit pull requests, and participate in discussions to help shape the project's future.
> > Stay Updated:
> > To stay informed about the latest developments and participate in discussions, please visit the new repository [link to new repository].

Thank you for a great proposal! Totally agree with you that the work he has done is invaluable and it should be done with respect and gratefulness.
