### ISSUE TITLE
Update README to clearify fork and differences to old project

### ISSUE THREAD

**Issue by XSpielinbox** [openhtmltopdf/openhtmltopdf#24]
The README hasn't been updated since this fork was made.

It at first therefore is not clear, that this is a community fork and what has been done since.

The changelog still states `head - 1.0.11-SNAPSHOT` at the top of the changelog, references `17 (early access)`, but no word of Java 21, etc.

Just some small changes would make it way more informative and clear in my opinion.

I can also start a PR for that.

**Comment by siegelzc** [comment]
Sure, I would welcome an update to the README
