### ISSUE TITLE
rgb(254 215 170 / var(--tw-bg-opacity)) is not supported

### ISSUE THREAD

**Issue by geertvanleemputten** [openhtmltopdf/openhtmltopdf#25]
Tailwind only generates rgb in the latest versions as opposed to adding the hex values in earlier versions.

eg:
.bg-orange-200 {
  --tw-bg-opacity: 1;
  background-color: rgb(254 215 170 / var(--tw-bg-opacity));
}

older version:
.bg-orange-200 {
    --bg-opacity: 1;
    background-color: #feebc8;
    background-color: rgba(254, 235, 200, var(--bg-opacity))
}

**Comment by siegelzc** [comment]
The CSS engine does not support CSS variables. Also, opacity is not supported either.

**Comment by geertvanleemputten** [comment]
I solved it with this tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/main/resources/templates/**/*.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {},
    fontFamily: {
      'poppins': ['Poppins'],
      'sans': ['Open Sans'],
      'roboto': ['Roboto'],
      'inter': ['Inter'],
    },
  },
  corePlugins: {
    textOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    placeholderOpacity: false,
    ringOpacity: false,
  },
  plugins: [],
}

The corePlugins settings made the hex color codes available again.
