### ISSUE TITLE
when will the releases of this repository available in maven central officially

### ISSUE THREAD

**Issue by ishmshra** [openhtmltopdf/openhtmltopdf#47]
Hi All,
Could you please let me know when will the releases of this repository available in maven central officially as I using the 1.0.10 version of openhtmltopdf (https://github.com/danfickle/openhtmltopdf) which I dont see any latest releases or commits since quite a long time. Should I continue to use the version 1.0.10 or are there any upcoming official stable releases of openhtmltopdf. I could see that there is a 1.1.4 version available in maven central. could we use this as a stable version in my project
Thanks.

**Comment by siegelzc** [comment]
Is this not working for you?

https://central.sonatype.com/artifact/io.github.openhtmltopdf

**Comment by ishmshra** [comment]
yes, it is working for me. Thanks.

**Comment by jochenberger** [comment]
I'm getting a 404 from that URL.

**Comment by siegelzc** [comment]
whoops
https://central.sonatype.com/artifact/io.github.openhtmltopdf/openhtmltopdf-core
