### ISSUE TITLE
Overflow hidden not applied

### ISSUE THREAD

**Issue by tschuehly** [openhtmltopdf/openhtmltopdf#54]
Hello everyone,

My HTML consists of many divs with a set size and overflow hidden, after each other.

Each div should represent one page. Sadly overflow hidden is not respected and if the image overlaps above it reaches into the previous page. In the browser it looks normally.
I also tried with contain: paint.

Is there a way to render pages individually?

**Comment by siegelzc** [comment]
Could you send the PDF file?

**Comment by tschuehly** [comment]
Thanks for the quick response.

Here is the PDF:
[1717874783067.pdf](https://github.com/user-attachments/files/15749442/1717874783067.pdf)

Here is the HTML:

https://gist.github.com/tschuehly/0f045955cc3e54c08ebf7e34d87bffe3

**Comment by siegelzc** [comment]
I can reproduce the issue.

**Comment by siegelzc** [comment]
Are you just trying to print these out?

**Comment by tschuehly** [comment]
> Are you just trying to print these out?

Well yes, they are automatically generated and then my customers print them out.

**Comment by siegelzc** [comment]
Openhtmltopdf uses a custom engine to render HTML/CSS (rathern than WebKit/Blink/etc.). This engine is obviously not as well maintained or fully featured, but it is much _lighter_, allowing it to run significantly faster than alternatives (e.g. there is no code paying any attention to JavaScript). As a result, some not-so-gentle massaging is required to achieve parity between the PDF output and what is seen in a web browser.

I see you're using "contain: paint" on the divs, but this is a new CSS feature which is not supported by this project. Replacing "contain: paint", with "overflow: hidden" gets you part of the way there, but the images won't be hidden without changing the images to use "position: relative" (I'm not really sure why).

If you do these two things there will be a blank page inserted between each desired page, so change the @page y-size to be 420px (equivalent to the height set on the divs), and the blank pages will disappear.

This doesn't get you to a perfect solution, but I think you should be able to touch up the image positioning and such yourself.

**Comment by tschuehly** [comment]
Thank you for the help!

I've tried it out with the HTML as you've described it: https://gist.github.com/tschuehly/a5c4e8ad19c50d8eba32a15d24e1937b
Sadly I couldn't get it to work. 
Any Ideas?

**Comment by siegelzc** [comment]
This file is incomplete. It is not valid HTML.

You also did not set `position: relative` like I suggested, and you did not change the page height value.
